### ISSUE TITLE
Add command to check quota in CLI to Docs (get started)

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/docs.formkiq.com#86]

**Comment by mfriesen** [comment]
aws service-quotas get-service-quota --service-code lambda --quota-code L-B99A9384 --region <AWS_REGION>

{
    "Quota": {
        "ServiceCode": "lambda",
        "ServiceName": "AWS Lambda",
        "QuotaArn": "arn:aws:servicequotas:us-west-2:XXXXXXX:lambda/L-B99A9384",
        "QuotaCode": "L-B99A9384",
        "QuotaName": "Concurrent executions",
        "Value": 1000.0,
        "Unit": "None",
        "Adjustable": true,
        "GlobalQuota": false,
        "UsageMetric": {
            "MetricNamespace": "AWS/Lambda",
            "MetricName": "ConcurrentExecutions",
            "MetricDimensions": {},
            "MetricStatisticRecommendation": "Maximum"
        },
        "QuotaAppliedAtLevel": "ACCOUNT"
    }
}
